apiVersion: v1
kind: Pod
metadata:
   name: dynamic-agents
   labels:
      app: dynamic-agents
spec:
  containers:
  - name: git
    image: bitnami/git:latest
    command:
    - cat 
    tty: true
  - name: maven
    image: maven:3.8.3-openjdk-17
    command:
    - cat 
    tty: true
    volumeMounts:
    - name: cache
      mountPath: /root/.m2/repository/   
  volumes:
  - name: cache
    persistentVolumeClaim:
      claimName: spring-petclinic-pvc
